name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Compile code
        run: npm run build

      - name: Deploy to Vercel
        uses: vercel/actions@main
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          args: '--prod'
